# Generated by Django 5.0.1 on 2024-03-06 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_blogger_details_blogdetails_bloggerdetails_and_more'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.TextField()),
                ('blog_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.blogdetails')),
            ],
        ),
    ]
