# Generated by Django 5.0.1 on 2024-03-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetails',
            name='blogtype',
            field=models.CharField(choices=[('foodblogs', 'Food-blogs'), ('travelblogs', 'Travel-blogs'), ('petsblogs', 'Pets-blogs')], default='foodblogs', max_length=20),
        ),
    ]
