# Generated by Django 5.0.1 on 2024-03-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_blogtype_blogdetails_blog_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogdetails',
            table='BlogDetails',
        ),
    ]
