# Generated by Django 5.0.1 on 2024-03-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_blogdetails_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='blog_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='blogger_details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
